name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: 2.9.8
      - name: Run Tests
        run: lein kaocha
